
new_options = trainingOptions('adam', ...
    'MaxEpochs',1500, ...
    'GradientThreshold',1, ...
    'InitialLearnRate',0.005, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',125, ...
    'LearnRateDropFactor',0.2, ...
    'Verbose',0, ...
    'Plots','training-progress');

layers=[sequenceInputLayer(7)
    fullyConnectedLayer(10)
reluLayer
    fullyConnectedLayer(1)
   reluLayer
regressionLayer]

net_adam=trainNetwork(data.in,data.out,layers,new_options)